# Web App Back End Tests

Tests for the back end of the Structure Relations web application.
Uses *RS.GJS_Struct_Tests.BRBL BH.dcm* file located in the *test_data* folder.

## 1. Import Required Libraries

First, let's import the necessary libraries including our custom DicomStructureFile class.

In [2]:
# Import required libraries
from typing import List, Tuple
#import sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import shapely

# Add the src directory to the Python path
#sys.path.append('src')

# Import our custom DicomStructureFile class
from dicom import DicomStructureFile

# Import related classes
from types_and_classes import SliceIndexType
from contours import ContourPoints
from contour_plotting import plot_roi_slice

from structure_set import StructureSet
from relations import RelationshipType

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
%matplotlib inline

In [4]:
# Define the path to the test DICOM file
tests_dir = Path.cwd() / r'Tests'
tests_dir = tests_dir.resolve()
test_file_name = 'RS.GJS_Struct_Tests.BRBL BH.dcm'

print(f"=== Loading DICOM file ===: {test_file_name}")
dicom_file = DicomStructureFile(
    top_dir=tests_dir,
    file_name=test_file_name
)
filtered_contours = dicom_file.filter_exclusions()

structure_set = StructureSet(dicom_structure_file=dicom_file)

INFO:dicom:Successfully loaded DICOM dataset from RS.GJS_Struct_Tests.BRBL BH.dcm

=== Loading DICOM file ===: RS.GJS_Struct_Tests.BRBL BH.dcm

INFO:dicom:Extracted 626 contours from 10 ROIs
INFO:dicom:Found 0 frame-of-reference matches and 0 other matches for structure set RS.GJS_Struct_Tests.BRBL BH.dcm
WARNING:dicom:No matching image files found, attempting to use structure dimensions
INFO:dicom:Calculated resolution from structure 'BODY': 0.1 cm/pixel
INFO:dicom:Calculated resolution from structure 'BODY': 0.1 cm/pixel
INFO:dicom:Filtered 0 contours from 1 excluded ROIs. Remaining: 626 contours from 9 ROIs
INFO:structure_set:Building StructureSet from 626 contour points

In [5]:
structure_set.summary()

,ROI,Name,Physical_Volume,Exterior_Volume,Hull_Volume,Num_Contours,Num_Slices
0,9,BODY,43449.753197,43449.753197,46139.282358,142,127
1,11,Cavity,74.997151,74.997151,83.028116,19,19
2,12,CTV Cavity,276.825057,276.825057,289.663130,29,29
3,13,eval PTV,432.802507,432.802507,447.067692,36,36
4,14,PTV Cavity,454.345283,454.345283,468.367192,36,36
5,17,Heart,805.989593,805.989593,810.463168,41,41
6,18,Lung B,5189.276155,5189.276155,6236.533126,208,103
7,19,Lung L,2460.921878,2460.921878,3068.969065,105,103
8,20,Lung R,2818.394331,2818.394331,3282.927210,107,99

In [18]:
structure_set.relationship_matrix

Empty DataFrame
Columns: []
Index: []

In [6]:
structure_set.summary().ROI.to_list()

[9, 11, 12, 13, 14, 17, 18, 19, 20]

In [10]:
row_rois = col_rois = [9, 11, 12, 13, 14, 17, 18, 19, 20]

In [7]:
structure_set.to_dict()

{'rows': [],
 'columns': [],
 'data': [],
 'row_names': [],
 'col_names': [],
 'colors': {}}

In [8]:
structure_set.structures[11]

In [16]:
all_rois = sorted(list(structure_set.structures.keys()))
all_names = [structure_set.structures[roi].name for roi in all_rois]

In [11]:
matrix = structure_set.get_relationship_matrix(row_rois, col_rois, use_symbols=False)

In [12]:
matrix

Empty DataFrame
Columns: []
Index: []